- name: Installing Java
  hosts: all
  become: true
  tasks:
    - name: Update apt-get
      apt:
        update_cache: yes

    - name: Check if Java is installed
      command: java -version
      register: java_check
      ignore_errors: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
      when: java_check.rc != 0
