- name: Install JFrog Artifactory
  hosts: all
  become: true
  tasks:
    - name: Check if JFrog Artifactory is installed
      command: systemctl status artifactory
      register: artifactory_check
      ignore_errors: yes

    - name: Install JFrog Artifactory
      shell: |
        curl -fL https://get.jfrog.io/artifactory/Artifactory-{{ version }}.rpm -O
        sudo yum localinstall -y Artifactory-{{ version }}.rpm
      args:
        executable: /bin/bash
      when: artifactory_check.rc != 0
      vars:
        version: "latest"
